### ISSUE TITLE
Publish new release version based on latest code

### ISSUE THREAD

**Issue by bmemartin** [manybrain/mailinator-python-client#2] opened 2022-07-18 03:39 UTC
The published version [0.0.4](https://pypi.org/project/mailinator-python-client-2/0.0.4/) does not contain the latest code changes. As a result commit [c44ceb6](https://github.com/manybrain/mailinator-python-client/commit/c44ceb6dc6264441361775c158c08f5cafc57212) is missing and response payloads are bring printed. Please publish a new version based on the current code base.

**Comment by joao-carloto** [comment] 2023-03-23 16:38
I would also request the same. I lost some time trying to run a piece of code from the  test_mailinator.py file, only to realise the corresponding feature was not yet published (GetMessageLinksRequest).
Thank you.

**Comment by marianmelnychuk** [comment] 2024-02-23 14:48
@wearingsocks @joao-carloto Thank you for bringing this to our attention. I apologize for the inconvenience caused by the outdated version of the package. We have addressed the issue by publishing a new version (0.0.6) containing the latest code changes, including commit c44ceb6.

You can now update to the latest version to access the updated functionality and fixes. If you encounter any further issues, please don't hesitate to let us know.

Closing this issue now as the problem has been resolved with the publication of version 0.0.6. Thank you for your patience and understanding.

**Closed as completed by marianmelnychuk** 2024-02-23 14:48 UTC
